### ISSUE TITLE
Portfolio: "Supplied" balance should always be >= "Collateral"

### ISSUE THREAD

**Issue by kcole16** [NearDeFi/burrow-cash#202]
### Overview

The "Supplied" balance of a given asset includes both the "Collateral" amount and the supplied, but not collateralized amount.

### Scenarios

If a user supplies 100 NEAR, then designates all of it as collateral:
`Collateral = 100 NEAR` and `Supplied = 100 NEAR`

If a user supplies 100 NEAR, then designates 50 as collateral:
`Collateral = 50 NEAR` and `Supplied = 100 NEAR`

**Comment by miaojiang** [comment]
@ciocan looks like it's done. Closing the item.
