### ISSUE TITLE
Deposit of NEAR issue

### ISSUE THREAD

**Issue by evgenykuzyakov** [NearDeFi/burrow-cash#221]
The deposit UI of NEAR doesn't display the correct balance. It only displays the native account balance, but doesn't take into account the balance of `wrap.near` token. Ideally we should sum the two balances together and present it to a user.

Once user selects the amount, figure out whether some part of the amount has to be wrapped first before deposit.

**Comment by miaojiang** [comment]
Closing. Duplicate of #228.
