### ISSUE TITLE
Not getting rewards

### ISSUE THREAD

**Issue by miaojiang** [NearDeFi/burrow-cash#261]
A few users have reported an issue of not getting rewards.

**Comment by miaojiang** [comment]
Looks like performing a UX action does the trick. Seems to be a UX-side bug. 

cc @ciocan feel free to ping me for a wallet that has this issue.

**Comment by ciocan** [comment]
fixed here:
https://github.com/NearDeFi/burrow-cash/commit/8b1b7132fdccf84d6276c7d16c6dc2f8daf6697c

the unclaimed supply rewards were not computed right
