### ISSUE TITLE
UI shows wNEAR but deposit only takes NEAR

### ISSUE THREAD

**Issue by mattlockyer** [NearDeFi/burrow-cash#262]
![image](https://user-images.githubusercontent.com/321340/161773397-8dab3cfc-348f-4f31-8dfd-15a7ec817f04.png)

Had a user send me this. Then tried on ref to wrap 1 N.

Basically, wNEAR doesn't show up to be able to deposit, only NEAR.

But the UI shows wNEAR, so they kind of assume they need to wrap it themselves first... if they are not newb.

How should this be handled? Open question I think I've seen discussed.

Feel free to cross-ref and close.

**Comment by miaojiang** [comment]
Closing this one. Please refer to #228.
