### ISSUE TITLE
Boosts: Rewards multipliers

### ISSUE THREAD

**Issue by H34D** [NearDeFi/burrow-cash#53]
Not logged in state: Don't show xBRRR boost column at all

Logged in: Show the user's actual multiplier

<img width="158" alt="Screenshot 2021-10-29 at 15 37 34" src="https://user-images.githubusercontent.com/13647606/139444817-e03b85f1-c905-4024-8bc9-80478a3099e9.png">

**Comment by miaojiang** [comment]
Stale item, closing.
