### ISSUE TITLE
Borrow limit not implemented

### ISSUE THREAD

**Issue by H34D** [NearDeFi/burrow-cash#59]
<img width="276" alt="Screenshot 2021-10-29 at 15 42 18" src="https://user-images.githubusercontent.com/13647606/139445579-8b06a6dd-09a5-43fc-91cf-3863378d1769.png">

**Comment by miaojiang** [comment]
@ciocan please confirm this is done and close the ticket.

**Comment by miaojiang** [comment]
Stale item, closing.
