### ISSUE TITLE
Borrow rewards APY not implemented

### ISSUE THREAD

**Issue by H34D** [NearDeFi/burrow-cash#61]
<img width="153" alt="Screenshot 2021-10-29 at 15 43 11" src="https://user-images.githubusercontent.com/13647606/139445728-03f0fa5a-8ce0-4f5d-9b49-6772e5d9b560.png">

@kcole16 what are the icons right next to the APY percent number? The tokens that can be used as collateral?

The dots represent the reward token icons

**Comment by miaojiang** [comment]
Closing this one. We can create a separate issue if we need to display tokens that are rewarded to users.
